swagger: "2.0"
info:
  description: "Bank API documentation for the transactions"
  version: "1.0.0"
  title: "Argent Bank transactions API doc"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/"
tags:
  - name: "transactions"
    description: "Operations to manage transactions"
schemes:
  - "https"
  - "http"
paths:
  # Endpoint for fetching all user transactions
  /transactions:
    get:
      # Security configuration for JWT authentication
      security:
        - Bearer: []
      tags:
        - "transactions"
      summary: "User Transactions API"
      description: "API for fetching all user transactions"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      responses:
        "200":
          description: "User transactions retrieved successfully"
          schema: 
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: "Transaction not found"
        "500":
          description: "Internal Server Error"
    post:
      # Security configuration for JWT authentication
      security: 
        - Bearer: []
      tags:
        - "transactions"
      summary: "Create a new transaction"
      description: "Endpoint to create a new transaction"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT Token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Transaction details"
          required: true
          schema:
            $ref: "#/definitions/TransactionDescription"
      responses:
        "201":
          description: "Successful Operation"
        "400":
          description: "Invalid Transaction Description supplied"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal server error"

  # Endpoint for getting a specific user transaction
  /transactions/{transactionId}:
    get:
      # Security configuration for JWT authentication
      security:
        - Bearer: []
      tags:
        - "transactions"
      summary: "User unique transaction"
      description: "Get transaction info"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "transactionId"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT Token"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: "Invalid Transaction Description supplied"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal server error"
    put:
      # Security configuration for JWT authentication
      security:
        - Bearer: []
      tags:
        - "transactions"
      summary: "Edit transaction"
      description: "Update transaction's description"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: "path"
          name: "transactionId"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT Token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Transaction details to update"
          required: true
          schema:
            $ref: "#/definitions/TransactionDescription"
      responses:
        "200":
          description: "Successful Operation"
        "400":
          description: "Invalid Transaction Description supplied"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal server error"

securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  TransactionsResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message: 
        type: "string"
      body: 
        $ref: "#/definitions/Transaction"
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
        description: "transaction ID"
      created:
        type: "string"
        description: "transaction date"
      description:
        type: "string"
        description: "transaction description"
      amount:
        type: "number"
        description: "transaction amount"
      balance:
        type: "number"
        description: "account balance after transaction"
      transactionType:
        type: "string"
        description: "transaction type"
      category:
        type: "string"
        description: "transaction category"
      note:
        type: "string"
        description: "user's notes for transaction"
  TransactionDescription:
    type: "object"
    properties:
      category:
        type: "string"
        description: "transaction's category"
      note:
        type: "string"
        description: "user's notes for transaction"
